projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  cf:
    schemaPath: src/generated/contentful.graphql
    extensions:
      endpoints:
        default:
          url: https://cdn.contentful.com/spaces/9t7hdjj3yor9/graphql/alpha?locale=en-US
          headers:
            Authorization: Bearer __CONTENTFUL_ACCESS_TOKEN__
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml